---
# tasks file for kvm-backup-lvm
- name: get vm configuration
  virt:
    name: "{{ vmname }}"
    command: get_xml
  register: xml

- name: create directory for backup
  file:
      path: "{{ dir_guest |mandatory }}" # required. Path to the file being managed.
      state: directory
  delegate_to: localhost

- name: saving configuration
  copy:
    content: "{{ xml.get_xml }}"
    dest: "{{ xml_file }}"
  delegate_to: localhost

- name: extracting disks from xml
  xml:
    path: "{{ xml_file }}"
    xpath: /domain/devices/disk/source
    content: attribute
  register: disks
  delegate_to: localhost

- name: print detected lvms
  debug:
    msg: "{{ item.source.dev }}"
  when: item.source.dev is defined
  loop: "{{ disks.matches }}"
  register: lvms

- name: set lvms
  set_fact:
    tags_dict: "{{ (tags_dict|default({}))|combine({item.source.dev: item.source.dev.split('/')[2]}) }}"
  loop: "{{ disks.matches }}"
  when: item.source.dev is defined

- name: print tags_dict
  debug:
    msg: "{{ tags_dict }}"

- name: Get vgs
  debug:
    msg: "{{ item.msg.split('/')[2] }}"
  loop: "{{ lvms.results }}"
  register: vgs
  when: item.msg is defined

- name: Show VGS
  debug:
    var: vgs

- name: display available space for vgs
  debug:
#    var: ansible_facts['lvm']['vgs']['Data']
    msg: "{{ item.value.free_g }}"
  when: item.key == vgs.results[0].msg
  register: available_space
  loop: "{{ ansible_facts['lvm']['vgs'] | dict2items }}"

- name: display available space for lvs
  debug:
  #    var: ansible_facts['lvm']['vgs']['Data']
    msg: "{{ item.value.size_g }}"
  register: lvm_spaces
  when: item.key == "zproxy_test"
  loop: "{{ ansible_facts['lvm']['lvs'] | dict2items }}"

- name: Join lvm with vgs
  debug:
    msg: "LVM: {{ item.0.item.key }} - Value: {{ item.0.item.value.size_g }} con VGS: {{ item.1.item.key }} - Value: {{ item.1.item.value.free_g }} "
  loop: "{{ lvm_spaces.results |product(available_space.results) |list }}"
  when:
    - item.0.item.key == "zproxy_test" and item.1.item.key == "Data"

- name: Validate space on vgs for snapshot to lvm
  assert:
    that:
      - "{{ item.0.item.value.size_g }} < {{ item.1.item.value.free_g }} "
    fail_msg: "The space is minor than 100"
    success_msg: "The space is major than 100"
  loop: "{{ lvm_spaces.results |product(available_space.results) |list }}"
  when:
    - item.0.item.key == "zproxy_test" and item.1.item.key == "Data"


