---
# tasks file for kvm-backup-lvm
- name: get vm configuration
  virt:
    name: "{{ vmname }}"
    command: get_xml
  register: xml

- name: create directory for backup
  file:
      path: "{{ dir_guest }}" # required. Path to the file being managed.
      state: directory
  delegate_to: localhost

- name: saving configuration
  copy:
    content: "{{ xml.get_xml }}"
    dest: "{{ xml_file }}"
  delegate_to: localhost

- name: extracting disks from xml
  xml:
    path: "{{ xml_file }}"
    xpath: /domain/devices/disk/source
    content: attribute
  register: disks
  delegate_to: localhost

- name: print xml
  debug:
    msg: "{{ disks }}"
