---
- name: Validate space on vgs for snapshot to lvm
  assert: # Validate the debug of this module
    that:
      - "{{ item.0.item.value.size_g }} < {{ item.1.item.value.free_g }} "
    fail_msg: "You can't create a snapshot"
    success_msg: "You can create a snapshot"
  loop: "{{ lvm_spaces.results |product(available_space.results) |list }}"
  when:
    # - item.0.item.key == lvs_name.1 and item.1.item.key == vgs_name.0
    - item.0.item.key == lvm_and_vgs.0 and item.1.item.key == lvm_and_vgs.1

