---
- name: Validate space on vgs for snapshot to lvm
  assert:
    that:
      - "{{ item.0.item.value.size_g }} < {{ item.1.item.value.free_g }} "
    fail_msg: "You can't create a snapshot"
    success_msg: "You can create a snapshot"
    quiet: true
  loop: "{{ lvm_spaces.results |product(available_space.results) |list }}"
  when:
    - item.0.item.key == lvm_and_vgs.0 and item.1.item.key == lvm_and_vgs.1

- name: Creating snapshot for {{ vmname }} and {{ lvm_and_vgs.0 }}
  lvol:
    vg: "{{ lvm_and_vgs.1 }}"
    lv: "{{ lvm_and_vgs.0 }}"
    snapshot: "{{ lvm_and_vgs.0 }}-snap"
    size: "{{ item.value.size_g }}G"
  loop: "{{ ansible_facts['lvm']['lvs'] | dict2items }}"
  when: item.key == lvm_and_vgs.0
